kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: tenant2-role
  namespace: tenant2
rules:
  - apiGroups: [""]
    resources: ["pods", "secrets"]
    verbs: ["get", "list", "watch"]
