kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: tenant2-role-binding
  namespace: tenant2
subjects:
  - kind: ServiceAccount
    name: tenant2-account
    namespace: tenant2
roleRef:
  kind: Role
  name: tenant2-role
  apiGroup: rbac.authorization.k8s.io
